name: M3U Lint and Sort

on:
  push:
    paths:
      - 'free.m3u'
  workflow_dispatch:

jobs:
  lint-and-sort:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Basic M3U cleanup
        run: node .github/scripts/cleanup-m3u.js free.m3u
        
      - name: Sort M3U file
        run: node .github/scripts/sort-m3u.js free.m3u

      - name: Split into country playlists
        run: node .github/scripts/countries.js free.m3u




      - name: Commit changes to files 
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated updates of M3U Files" && git push)

